# Usa una imagen base de PostgreSQL
FROM postgres:latest

# Variables de entorno para configurar la base de datos
ENV POSTGRES_DB=tickets-clients
ENV POSTGRES_USER=usrtck
ENV POSTGRES_PASSWORD=usr12334

# Expone el puerto por defecto de PostgreSQL
EXPOSE 5432
